server:
  port: 8080
  servlet:
    context-path: /xwj-property-payment

spring:
  profiles:
    active: local
  application:
    name: xwj-property-payment

swagger:
  basePackage: com.joy
  title: 通用订单管理组件API
  description: <b>通用订单管理组件API</b><br/>
  version: 1.0-SNAPSHOT
  contactName: KylerTien
  contactEmail: 870354954@qq.com