spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: mymysql
    driverClassName: com.mysql.jdbc.Driver
